export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      colors: {
        background: '#0b1326',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'inverse-on-surface': '#283044',
        'inverse-primary': '#0053db',
        'inverse-surface': '#dae2fd',
        'on-background': '#dae2fd',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'on-primary': '#002a78',
        'on-primary-container': '#eeefff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'on-secondary': '#182d63',
        'on-secondary-container': '#a4b6f5',
        'on-secondary-fixed': '#00174b',
        'on-secondary-fixed-variant': '#31447b',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c3c6d7',
        'on-tertiary': '#581e00',
        'on-tertiary-container': '#ffede6',
        'on-tertiary-fixed': '#360f00',
        'on-tertiary-fixed-variant': '#7d2d00',
        outline: '#8d90a0',
        'outline-variant': '#434655',
        primary: '#b4c5ff',
        'primary-container': '#2563eb',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        secondary: '#b4c5ff',
        'secondary-container': '#33467e',
        'secondary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b4c5ff',
        surface: '#0b1326',
        'surface-bright': '#31394d',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-container-low': '#131b2e',
        'surface-container-lowest': '#060e20',
        'surface-dim': '#0b1326',
        'surface-tint': '#b4c5ff',
        'surface-variant': '#2d3449',
        tertiary: '#ffb596',
        'tertiary-container': '#bc4800',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#ffb596'
      },
      boxShadow: {
        'ambient': '0 20px 40px rgba(0, 0, 0, 0.4)'
      }
    },
  },
  plugins: [],
}
