import os
from dotenv import load_dotenv
from openai import OpenAI

# ==========================================
# 1. Initialization & API Security
# ==========================================
print("Booting up the Generator (OpenRouter: Llama 3 70B)...")
load_dotenv()

api_key = os.getenv("OPENROUTER_API_KEY")
if not api_key:
    print("🚨 ERROR: OPENROUTER_API_KEY not found! Check your .env file.")
else:
    print(f"✅ API Key loaded successfully (Starts with: {api_key[:10]}...)")

# OpenRouter seamlessly uses the standard OpenAI SDK structure
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key,
)

# The chosen open-weight champion for elite reasoning and strict RAG compliance
MODEL_NAME = "meta-llama/llama-3.1-70b-instruct"

# ==========================================
# 2. Event-Driven Chat Engine
# ==========================================
def chat_about_insight(user_message, insight_data, news_snippets, chat_history):
    """
    Acts as the conversational engine. Takes the quantitative insight, 
    the procured news, and previous chat turns to answer the user.
    """
    # 1. Format the verified news context
    formatted_news = "\n".join([f"[{i+1}] {s}" for i, s in enumerate(news_snippets)])
    if not formatted_news:
        formatted_news = "NO RECENT NEWS FOUND IN DATABASE."

    # 2. Build the System Prompt with STRICT Quantitative Boundaries
    system_prompt = f"""You are Sentinel AI, an elite financial analyst.
You are currently briefing a user on the following Market Insight generated by our quantitative engine:

[TARGET METADATA]
- Ticker: {insight_data.get('ticker', 'GENERAL')}
- Sector: {insight_data.get('sector', 'Unknown')}
- Timestamp: {insight_data.get('timestamp', 'Recent')}

[THE QUANTITATIVE INSIGHT]
"{insight_data.get('insight_text', '')}"

[VERIFIED NEWS CONTEXT]
{formatted_news}

CRITICAL INSTRUCTIONS:
1. Your ONLY job is to explain if the Verified News Context justifies the Quantitative Insight. 
2. DO NOT generate your own technical analysis, hypotheses, or market predictions. You are strictly forbidden from extrapolating beyond the provided data.
3. If the news context clearly explains the technical move, summarize the fundamental catalyst in 3 concise bullet points. Cite sources.
4. If the news context is empty or unrelated, you MUST state: "No fundamental catalyst found in recent news to explain this quantitative event. This appears to be a purely technical or systemic move."
5. Do not guess. Be concise, objective, and rigidly analytical.
"""

    # 3. Assemble the conversation history for conversational memory
    messages = [{"role": "system", "content": system_prompt}]
    
    # Inject the last 3 turns of conversation to give the AI context without blowing up the token count
    for turn in chat_history[-3:]:
        messages.append({"role": "user", "content": turn['user']})
        messages.append({"role": "assistant", "content": turn['ai']})
        
    # Inject the live user question
    messages.append({"role": "user", "content": user_message})

    # 4. Fire to OpenRouter API
    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=messages,
            temperature=0.3, # Slightly higher than 0.1 so it can converse naturally while staying factual
            max_tokens=400,  
        )
        return response.choices[0].message.content
        
    except Exception as e:
        return f"Sentinel AI Error: Unable to reach OpenRouter API. ({str(e)})"

# ==========================================
# 3. Local Integrity Test
# ==========================================
if __name__ == "__main__":
    # A quick mock test to ensure the prompt formatting and API call work in isolation
    mock_insight = {
        "ticker": "RELIANCE.NS",
        "sector": "Conglomerate",
        "insight_text": "Sudden bullish volume spike. Price broke above the 50-day SMA.",
        "timestamp": "2026-03-27 14:30:00"
    }
    mock_news = ["[Source: ET Markets, Date: 2026-03-27] Reliance announces massive new green energy plant."]
    mock_history = []
    
    print("\n[Pipeline] Testing Event-Driven Generation Module...")
    test_query = "Explain why this insight is occurring based on the latest news. Give me 3 bullet points."
    
    answer = chat_about_insight(test_query, mock_insight, mock_news, mock_history)
    
    print("\n" + "="*70)
    print("🤖 MOCK SENTINEL BRIEFING:")
    print("="*70)
    print(answer)
    print("="*70)